language: ruby
rvm:
  - 2.3.4
  - 2.3.8
  - 2.4.5
  - 2.5.3
script: bundle exec rake
install:
  - "gem install bundler"
  - "bundle install --jobs=3 --retry=3"
notifications:
  recipients:
    - shane@teamsnap.com
