language: ruby
rvm:
  - 2.3.1
  - 2.4.4
  - 2.5.1
script: bundle exec rake
install:
  - "gem install bundler"
  - "bundle install --jobs=3 --retry=3"
notifications:
  recipients:
    - shane@teamsnap.com
    - ryan.williams@teamsnap.com
